refactor: started parse refactor

diff --git a/h2mm b/h2mm
--- a/h2mm
+++ b/h2mm
@@ -97,14 +97,28 @@ function get_entry_from_db_by_nexus_mod_id() {
 	echo "$(awk -F, -v pos="$DB_MOD_NEXUS_ID_POS" -v id="$1" 'NR > 1 && $pos == id {print $0}' "$DB_FILE")"
 }
 
-function parse_help_no_arguments() {
-	display_help="$1"
-	[[ "$2" == "--help" || "$2" == "-h" ]] && { $display_help; exit 0; }
-}
-
-function parse_help_has_arguments() {
-	display_help="$1"
-	[[ $# -eq 1 || "$2" == "--help" || "$2" == "-h"  ]] && { $display_help; exit 0; }
+function parse() {
+	local type="$1"
+	shift
+	# need a way to specify multiple options
+	case "$type" in
+		"help")
+			display_help="$1"
+			[[ "$2" == "ARGS" && $# -eq 2 ]] || [[ "$2" == "--help" || "$2" == "-h" ]] && { $display_help; exit 0; }
+			;;
+		"name")
+			if [[ "$1" == "--name" || "$1" == "-n" ]]; then
+				[[ -z "$2" ]] && { log ERROR "Name is required."; exit 1; }
+				mod_name="$2"; shift 2;
+			fi
+			;;
+		"index")
+			if [[ "$1" == "--index" || "$1" == "-i" ]]; then
+				[[ -z "$2" ]] && { log ERROR "Index is required."; exit 1; }
+				mod_index="$2"; shift 2;
+			fi
+			;;
+	esac
 }
 
 function h() {
@@ -753,7 +767,7 @@ function downgrade_mods() {
 }
 
 function mod_enable() {
-	parse_help_has_arguments display_help_enable "$@"
+	parse help display_help_enable ARGS "$@"
 	local mod_name=""
 	local mod_index=""
 
@@ -826,7 +840,7 @@ function mod_enable() {
 }
 
 function mod_disable() {
-	parse_help_has_arguments display_help_disable "$@"
+	parse help display_help_disable ARGS "$@"
 	local mod_name=""
 	local mod_index=""
 
@@ -891,7 +905,7 @@ function mod_disable() {
 }
 
 function mod_reset() {
-	parse_help_no_arguments display_help_reset "$@"
+	parse help display_help_reset "$@"
 	local no_path_reset=false; [[ "$1" == "--no-path-reset" ]] && no_path_reset=true
 
 	log PROMPT "Are you sure you want to ${RED}reset${NC} all installed mods? (Y/n): "
@@ -909,7 +923,7 @@ function mod_reset() {
 }
 
 function mod_install() {
-	parse_help_has_arguments display_help_install "$@"
+	parse help display_help_install ARGS "$@"
 	local mod_name=""
 	local mod_dir=()
 	local mod_files=()
@@ -1183,7 +1197,7 @@ function mod_install() {
 }
 
 function mod_uninstall() {
-	parse_help_has_arguments display_help_uninstall "$@"
+	parse help display_help_uninstall ARGS "$@"
 	local mod_name=""
 	local mod_index=""
 
@@ -1240,7 +1254,7 @@ function mod_uninstall() {
 }
 
 function mod_list() {
-	parse_help_no_arguments display_help_list "$@"
+	parse help display_help_list "$@"
     local verbose=false
 
     # parse arguments
@@ -1288,7 +1302,7 @@ function mod_list() {
 }
 
 function mod_export() {
-	parse_help_no_arguments display_help_export "$@"
+	parse help display_help_export "$@"
 	local save_dir=${BACKUPS_DIR}
 	local archive_name="HD2-Mods-$(date +%Y-%m-%d_%H-%M-%S)"
 	local modpack_export=false
@@ -1344,7 +1358,7 @@ function mod_export() {
 }
 
 function mod_import() {
-	parse_help_has_arguments display_help_import "$@"
+	parse help display_help_import ARGS "$@"
 	local modpack=false; [[ "$1" == "--modpack" ]] && { modpack=true; shift 1; }
 
 	# check if the file exists
@@ -1403,7 +1417,7 @@ function mod_import() {
 }
 
 function mod_order {
-	parse_help_has_arguments display_help_order "$@"
+	parse help display_help_order ARGS "$@"
 	local mod_name=""
 	local mod_index=""
 	local new_index=""
@@ -1569,7 +1583,7 @@ function mod_order {
 }
 
 function mod_rename() {
-	parse_help_has_arguments display_help_rename "$@"
+	parse help display_help_rename ARGS "$@"
 	local mod_name=""
 	local new_mod_name=""
 	local mod_index=""
@@ -1613,7 +1627,7 @@ function mod_rename() {
 # --- Modpack management ---
 
 function modpack() {
-	parse_help_has_arguments display_help_modpack "$@"
+	parse help display_help_modpack ARGS "$@"
 
 	# parse arguments
 	case "$1" in
@@ -1646,7 +1660,7 @@ function modpack() {
 }
 
 function modpack_list() {
-	parse_help_no_arguments display_help_modpack_list "$@"
+	parse help display_help_modpack_list "$@"
 	local verbose=false
 
 	# parse arguments
@@ -1691,7 +1705,7 @@ function modpack_list() {
 }
 
 function modpack_create() {
-	parse_help_has_arguments display_help_modpack_create "$@"
+	parse help display_help_modpack_create ARGS "$@"
 	local modpack_name=""
 
 	# parse arguments
@@ -1768,7 +1782,7 @@ function modpack_create() {
 }
 
 function modpack_switch() {
-	parse_help_has_arguments display_help_modpack_switch "$@"
+	parse help display_help_modpack_switch ARGS "$@"
 	local modpack_name=""
 	local modpack_index=""
 
@@ -1805,7 +1819,7 @@ function modpack_switch() {
 }
 
 function modpack_reset() {
-	parse_help_no_arguments display_help_modpack_reset "$@"
+	parse help display_help_modpack_reset "$@"
 
 	log PROMPT "Are you sure you want to ${RED}reset${NC} all installed modpacks? (Y/n): "
 	read confirm
@@ -1823,7 +1837,7 @@ function modpack_reset() {
 }
 
 function modpack_delete() {
-	parse_help_has_arguments display_help_modpack_delete "$@"
+	parse help display_help_modpack_delete ARGS "$@"
 	local modpack_name=""
 	local modpack_index=""
 
@@ -1858,7 +1872,7 @@ function modpack_delete() {
 }
 
 function modpack_overwrite() {
-	parse_help_has_arguments display_help_modpack_overwrite "$@"
+	parse help display_help_modpack_overwrite ARGS "$@"
 	local modpack_name=""
 	local modpack_index=""
 
@@ -1914,7 +1928,7 @@ function self_update() {
 # --- Nexus Mods Integration ---
 
 function nexus_setup() {
-	parse_help_no_arguments display_help_nexus_setup "$@"
+	parse help display_help_nexus_setup "$@"
 	local nexus_api_key=""
 
 	log INFO "This is the setup wizard for the ${ORANGE}Nexus Mods${NC} integration."
@@ -2155,7 +2169,7 @@ function check_for_h2mm_update() {
 # --- Main ---
 
 function main() {
-	parse_help_has_arguments display_help_main "$@"
+	parse help display_help_main ARGS "$@"
 
 	command="$1"; shift
 
